alias: notify when cleaning started
trigger:
  platform: state
  entity_id: vacuum.xiaomi_vacuum_cleaner
  to: 'cleaning'
action:
  - service: telegram_bot.send_message
    data:
      message: ðŸ¤– Cleanup started
