alias: notify when hass is being shutdown
trigger:
  platform: homeassistant
  event: shutdown
action:
  - service: telegram_bot.send_message
    data:
      target:
        - !secret telegram_chat_id_admin
        - !secret telegram_chat_id_ksenia
      title: 'â— <b>Stopping server!</b>'
      message: Home Assistant server is being shutdown
